
services:
  - type: web
    name: shelfmaster-api
    env: node
    region: oregon
    plan: free
    root: .
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shelfmaster-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: shelfmaster-db
    region: oregon
    plan: free
    databaseName: shelfmaster
    user: admin
